export type ReportCard = {
  href: string;
  title: string;
  description: string;
  group: string;
};

export const REPORTS: ReportCard[] = [
  { href: "/reports/view/stock-position", title: "Stock position", description: "Customer × product, tank dips, line content, gain/loss, ullage.", group: "Stock" },
  { href: "/reports/view/eom-stock", title: "End of month stock", description: "Customer balances as of a cutoff date, pivoted by product.", group: "Stock" },
  { href: "/reports/view/balances-status", title: "Balances with status", description: "Local, transit, mining, and proration quantities.", group: "Stock" },
  { href: "/reports/view/customer-range", title: "Customer range", description: "In / out / net stock for a date range.", group: "Stock" },
  { href: "/reports/view/customer-statement", title: "Customer stock statement", description: "Opening, reception, deliveries, adjustments, closing.", group: "Stock" },
  { href: "/reports/view/cargo-tracking", title: "Cargo tracking", description: "Open parcels by customer, vessel, and status.", group: "Stock" },
  { href: "/reports/view/vessel-parcel", title: "Vessel / parcel movement", description: "Balances by vessel and status for billing.", group: "Stock" },
  { href: "/reports/view/stock-movement", title: "Stock movement subsidiary", description: "Monthly opening / movements / closing by customer.", group: "Stock" },
  { href: "/reports/view/stock-aging", title: "Stock aging", description: "Open parcels by days since vessel date.", group: "Stock" },
  { href: "/reports/view/daily-throughput", title: "Daily throughput", description: "Receipts, loading, pump-over, and ITT by day.", group: "Stock" },
  { href: "/reports/view/tank-ullage", title: "Tank ullage", description: "Capacity, latest dip, and remaining space.", group: "Stock" },
  { href: "/reports/view/sbm-reception", title: "SBM reception", description: "Approved SBM vessel receipts.", group: "Reception" },
  { href: "/reports/view/koj-reception", title: "KOJ reception", description: "Approved KOJ vessel receipts.", group: "Reception" },
  { href: "/reports/view/sbm-monthly", title: "SBM monthly reception", description: "Depot × vessel crosstab for a month.", group: "Reception" },
  { href: "/reports/view/koj-monthly", title: "KOJ monthly reception", description: "Depot × vessel crosstab for a month.", group: "Reception" },
  { href: "/reports/view/market-share", title: "Market share", description: "Ships and volume by customer and route.", group: "Reception" },
  { href: "/reports/view/market-share-ships", title: "Received ships market share", description: "TIPER vs other terminals per ship (optional SBM or KOJ).", group: "Reception" },
  { href: "/reports/view/sbm-ships-share", title: "SBM received ships market share", description: "Single Buoy Mooring vessels — TIPER vs other terminals per ship.", group: "Reception" },
  { href: "/reports/view/koj-ships-share", title: "KOJ received ships market share", description: "Kurasini Oil Jetty vessels — TIPER vs other terminals per ship.", group: "Reception" },
  { href: "/reports/view/market-share-monthly", title: "Market share per month", description: "TIPER vs others and financial hold by month.", group: "Reception" },
  { href: "/reports/view/sbm-monthly-share", title: "SBM market share per month", description: "SBM TIPER vs others and financial hold by month.", group: "Reception" },
  { href: "/reports/view/koj-monthly-share", title: "KOJ market share per month", description: "KOJ TIPER vs others and financial hold by month.", group: "Reception" },
  { href: "/reports/view/sbm-receipts", title: "SBM receipts (TIPER vs others)", description: "SBM quantities at TIPER vs other terminals — period and cumulative.", group: "Reception" },
  { href: "/reports/view/koj-receipts", title: "KOJ receipts (TIPER vs others)", description: "KOJ quantities at TIPER vs other terminals — period and cumulative.", group: "Reception" },
  { href: "/reports/view/srt-vessels", title: "SRT vessel report", description: "Single Receiving Terminal vessels with status and financial hold.", group: "Reception" },
  { href: "/reports/view/periodic-stock-status", title: "Periodic stock status", description: "On-hand by transit / local / mining, receipts, hold, and SRT volume.", group: "Stock" },
  { href: "/reports/view/gain-loss", title: "Gain / loss", description: "Book stock versus physical dips for the selected period.", group: "Stock" },
  { href: "/reports/view/ewura-weekly", title: "EWURA weekly stock", description: "Customer code, name, stored quantity by status and financial hold.", group: "Stock" },
  { href: "/reports/view/pbpa-weekly", title: "PBPA weekly book stock", description: "System book stock by product and status, with overall total.", group: "Stock" },
  { href: "/reports/view/customer-stock", title: "Individual customer stock", description: "Balances, flows, hold, and transit destinations (Congo, Malawi, Zambia, …).", group: "Stock" },
  { href: "/reports/view/daily-mass-balance", title: "Daily book stock mass balance", description: "Daily book versus dip by product with cumulative gain/loss.", group: "Stock" },
  { href: "/reports/view/monthly-confirmation", title: "Monthly stock confirmation", description: "Opening, receipts, adjustments, pump-overs, and closing.", group: "Stock" },
  { href: "/reports/view/itt-summary", title: "ITT summary", description: "Inter-customer transfers with approval reference.", group: "Stock" },
  { href: "/reports/view/hold-register", title: "Financial hold register", description: "Open parcels still on financial hold.", group: "Stock" },
  { href: "/reports/view/reservation-exposure", title: "Open reservations", description: "Soft holds taken when an order starts.", group: "Stock" },
  { href: "/reports/view/pump-over-loading", title: "Pump-over & loading events", description: "Posted gantry and pump-over events.", group: "Stock" },
  { href: "/reports/view/pump-over-omc", title: "Pump-over & loading to OMCs", description: "AGO/PMS transit and local by customer.", group: "Reception" },
  { href: "/reports/view/pump-over-status", title: "Pump-over to terminals", description: "TIPER to other terminals by depot and transit / local / mining.", group: "Reception" },
  { href: "/reports/view/billing-summary", title: "Billing summary", description: "Runs by fee, currency, and status.", group: "Billing" },
  { href: "/reports/view/billing-list", title: "Billing / invoice list", description: "Billing runs for a daily, monthly, or yearly date range.", group: "Billing" },
  { href: "/reports/view/billing-by-trade", title: "Billing by class of trade", description: "Amounts grouped by class of trade and fee.", group: "Billing" },
  { href: "/reports/view/billing-by-product", title: "Billing by product", description: "Amounts grouped by product and fee.", group: "Billing" },
  { href: "/reports/view/billing-exceptions", title: "Billing exceptions", description: "Waivers and exceptions still on file.", group: "Billing" },
  { href: "/reports/view/license-expiry", title: "EWURA license expiry", description: "Licensee, number, class, expiry, and days remaining. Filter by class and status.", group: "Master" },
  { href: "/reports/view/open-orders", title: "Open orders", description: "ILR and pump-over still in progress.", group: "Gantry" },
  { href: "/reports/view/workflow-aging", title: "Workflow aging", description: "Open approvals and days waiting.", group: "Access" },
  { href: "/reports/view/customers", title: "Customers", description: "OMC customers — code, licence, TIN, and contact. Filter by active status.", group: "Master" },
  { href: "/reports/view/products", title: "Products", description: "AGO, PMS, and other stock items. Filter by active status and category.", group: "Master" },
  { href: "/reports/view/vessels", title: "Vessels", description: "Vessels that discharge at TIPER. Filter by active status.", group: "Master" },
  { href: "/reports/view/drivers", title: "Drivers", description: "Gantry drivers — licence, expiry, and phone. Filter by active status.", group: "Master" },
  { href: "/reports/view/trucks", title: "Trucks", description: "Horse and trailer plates by vehicle type. Filter by active status.", group: "Master" },
  { href: "/reports/view/transporters", title: "Haulers", description: "Haulers — TIN, phone, and licence. Filter by active status.", group: "Master" },
  { href: "/reports/view/depots", title: "Depots", description: "TIPER and destination depots. Filter by active status.", group: "Master" },
  { href: "/reports/view/tanks", title: "Tanks", description: "Shore tanks with product and capacities in litres. Filter by active status.", group: "Master" },
  { href: "/reports/view/itts", title: "In-tank transfers", description: "Ownership transfers between customers.", group: "Documents" },
  { href: "/reports/view/pump-over-requests", title: "Pump-over requests", description: "Pipeline delivery orders (DR).", group: "Documents" },
  { href: "/reports/view/pump-over-reports", title: "Pump-over reports", description: "Executed pump-over delivery reports.", group: "Documents" },
  { href: "/reports/view/yearly-loading", title: "Yearly loading summary", description: "AGO/PMS local and transit by month.", group: "Gantry" },
  { href: "/reports/view/monthly-loading", title: "Monthly loading summary", description: "Loaded trucks for a calendar month.", group: "Gantry" },
  { href: "/reports/view/daily-loading", title: "Daily loaded trucks", description: "Trucks and volumes for one loading day.", group: "Gantry" },
  { href: "/reports/view/loading-plan", title: "Loading plan", description: "Open gantry lines not yet loaded as of a date.", group: "Gantry" },
  { href: "/reports/view/transit-destination", title: "Transit by destination", description: "Transit loadings by customer and destination.", group: "Gantry" },
  { href: "/reports/view/ewura-loaded-trucks", title: "EWURA loaded trucks", description: "Daily loaded trucks for the regulator.", group: "Gantry" },
  { href: "/reports/view/marked-fuel", title: "Marked / local fuel", description: "Local (TBS-marked) loadings split 1–14 and 15–end.", group: "Gantry" },
  { href: "/reports/view/glr-status", title: "ILR loading status", description: "Loading-request status for a date range.", group: "Gantry" },
  { href: "/reports/view/glr-approvals", title: "ILR approvals", description: "Approved and completed loading requests.", group: "Gantry" },
  { href: "/reports/view/truck-seals", title: "Loaded truck seals", description: "Top, dip, and bottom seals on completed loads.", group: "Gantry" },
  { href: "/reports/view/glr-document", title: "ILR document", description: "Print an internal loading request by UID or number.", group: "Documents" },
  { href: "/reports/view/delivery-note", title: "Delivery note", description: "Delivery note for a completed compartmentalization.", group: "Documents" },
  { href: "/reports/view/gate-in", title: "Gate-in pass", description: "Gate-in pass for a running load.", group: "Documents" },
  { href: "/reports/view/gate-out", title: "Gate-out pass", description: "Gate-out pass for a loaded truck.", group: "Documents" },
  { href: "/reports/view/pump-over-document", title: "Pump-over request", description: "Pipeline delivery request (DR).", group: "Documents" },
  { href: "/reports/view/pump-over-report", title: "Pump-over report", description: "Executed pump-over delivery report.", group: "Documents" },
  { href: "/reports/view/itt-document", title: "ITT document", description: "In-tank transfer between customers.", group: "Documents" },
  { href: "/reports/view/receipt-document", title: "Vessel receipt", description: "Print an internal or external vessel receipt.", group: "Documents" },
  { href: "/reports/view/zerolization-document", title: "Zerolization", description: "Print a vessel consolidation.", group: "Documents" },
  { href: "/reports/view/hold-release-document", title: "Financial hold release", description: "Print a financial-hold release.", group: "Documents" },
  { href: "/reports/users", title: "System users", description: "Access review listing.", group: "Access" },
  { href: "/reports/roles", title: "Roles & permissions", description: "Permissions grouped by module.", group: "Access" },
  { href: "/reports/audit-activity", title: "Audit activity", description: "Who did what — filter by actor, action, or module.", group: "Access" },
];

export const REPORT_GROUPS = ["Stock", "Reception", "Gantry", "Billing", "Master", "Documents", "Access"] as const;

export const STOCK_REPORT_GROUPS = ["Stock", "Reception", "Gantry", "Documents", "Master"] as const;

export const FINANCE_REPORT_GROUPS = ["Billing"] as const;
