/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AppSplatRouteImport } from "./routes/_app/$"
import { Route as AppBillingRouteImport } from "./routes/_app/billing"
import { Route as AppDashboardRouteImport } from "./routes/_app/dashboard"
import { Route as AppEwuraRouteImport } from "./routes/_app/ewura"
import { Route as AppAccessRolesRouteImport } from "./routes/_app/access.roles"
import { Route as AppAccessUsersRouteImport } from "./routes/_app/access.users"
import { Route as AppGantryLoadingsRouteImport } from "./routes/_app/gantry.loadings"
import { Route as AppStockReceiptsRouteImport } from "./routes/_app/stock.receipts"
import { Route as AppStockTanksRouteImport } from "./routes/_app/stock.tanks"
import { Route as AppTerminalPumpoverRouteImport } from "./routes/_app/terminal.pumpover"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: "/billing",
  path: "/billing",
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AppRoute,
} as any)
const AppEwuraRoute = AppEwuraRouteImport.update({
  id: "/ewura",
  path: "/ewura",
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRolesRoute = AppAccessRolesRouteImport.update({
  id: "/access/roles",
  path: "/access/roles",
  getParentRoute: () => AppRoute,
} as any)
const AppAccessUsersRoute = AppAccessUsersRouteImport.update({
  id: "/access/users",
  path: "/access/users",
  getParentRoute: () => AppRoute,
} as any)
const AppGantryLoadingsRoute = AppGantryLoadingsRouteImport.update({
  id: "/gantry/loadings",
  path: "/gantry/loadings",
  getParentRoute: () => AppRoute,
} as any)
const AppStockReceiptsRoute = AppStockReceiptsRouteImport.update({
  id: "/stock/receipts",
  path: "/stock/receipts",
  getParentRoute: () => AppRoute,
} as any)
const AppStockTanksRoute = AppStockTanksRouteImport.update({
  id: "/stock/tanks",
  path: "/stock/tanks",
  getParentRoute: () => AppRoute,
} as any)
const AppTerminalPumpoverRoute = AppTerminalPumpoverRouteImport.update({
  id: "/terminal/pumpover",
  path: "/terminal/pumpover",
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/$": typeof AppSplatRoute
  "/billing": typeof AppBillingRoute
  "/dashboard": typeof AppDashboardRoute
  "/ewura": typeof AppEwuraRoute
  "/access/roles": typeof AppAccessRolesRoute
  "/access/users": typeof AppAccessUsersRoute
  "/gantry/loadings": typeof AppGantryLoadingsRoute
  "/stock/receipts": typeof AppStockReceiptsRoute
  "/stock/tanks": typeof AppStockTanksRoute
  "/terminal/pumpover": typeof AppTerminalPumpoverRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/$": typeof AppSplatRoute
  "/billing": typeof AppBillingRoute
  "/dashboard": typeof AppDashboardRoute
  "/ewura": typeof AppEwuraRoute
  "/access/roles": typeof AppAccessRolesRoute
  "/access/users": typeof AppAccessUsersRoute
  "/gantry/loadings": typeof AppGantryLoadingsRoute
  "/stock/receipts": typeof AppStockReceiptsRoute
  "/stock/tanks": typeof AppStockTanksRoute
  "/terminal/pumpover": typeof AppTerminalPumpoverRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_app": typeof AppRouteWithChildren
  "/login": typeof LoginRoute
  "/_app/$": typeof AppSplatRoute
  "/_app/billing": typeof AppBillingRoute
  "/_app/dashboard": typeof AppDashboardRoute
  "/_app/ewura": typeof AppEwuraRoute
  "/_app/access/roles": typeof AppAccessRolesRoute
  "/_app/access/users": typeof AppAccessUsersRoute
  "/_app/gantry/loadings": typeof AppGantryLoadingsRoute
  "/_app/stock/receipts": typeof AppStockReceiptsRoute
  "/_app/stock/tanks": typeof AppStockTanksRoute
  "/_app/terminal/pumpover": typeof AppTerminalPumpoverRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/$"
    | "/billing"
    | "/dashboard"
    | "/ewura"
    | "/access/roles"
    | "/access/users"
    | "/gantry/loadings"
    | "/stock/receipts"
    | "/stock/tanks"
    | "/terminal/pumpover"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/$"
    | "/billing"
    | "/dashboard"
    | "/ewura"
    | "/access/roles"
    | "/access/users"
    | "/gantry/loadings"
    | "/stock/receipts"
    | "/stock/tanks"
    | "/terminal/pumpover"
  id:
    | "__root__"
    | "/"
    | "/_app"
    | "/login"
    | "/_app/$"
    | "/_app/billing"
    | "/_app/dashboard"
    | "/_app/ewura"
    | "/_app/access/roles"
    | "/_app/access/users"
    | "/_app/gantry/loadings"
    | "/_app/stock/receipts"
    | "/_app/stock/tanks"
    | "/_app/terminal/pumpover"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/$": {
      id: "/_app/$"
      path: "/$"
      fullPath: "/$"
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/billing": {
      id: "/_app/billing"
      path: "/billing"
      fullPath: "/billing"
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/dashboard": {
      id: "/_app/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/ewura": {
      id: "/_app/ewura"
      path: "/ewura"
      fullPath: "/ewura"
      preLoaderRoute: typeof AppEwuraRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/access/roles": {
      id: "/_app/access/roles"
      path: "/access/roles"
      fullPath: "/access/roles"
      preLoaderRoute: typeof AppAccessRolesRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/access/users": {
      id: "/_app/access/users"
      path: "/access/users"
      fullPath: "/access/users"
      preLoaderRoute: typeof AppAccessUsersRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/gantry/loadings": {
      id: "/_app/gantry/loadings"
      path: "/gantry/loadings"
      fullPath: "/gantry/loadings"
      preLoaderRoute: typeof AppGantryLoadingsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/stock/receipts": {
      id: "/_app/stock/receipts"
      path: "/stock/receipts"
      fullPath: "/stock/receipts"
      preLoaderRoute: typeof AppStockReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/stock/tanks": {
      id: "/_app/stock/tanks"
      path: "/stock/tanks"
      fullPath: "/stock/tanks"
      preLoaderRoute: typeof AppStockTanksRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/terminal/pumpover": {
      id: "/_app/terminal/pumpover"
      path: "/terminal/pumpover"
      fullPath: "/terminal/pumpover"
      preLoaderRoute: typeof AppTerminalPumpoverRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEwuraRoute: typeof AppEwuraRoute
  AppAccessRolesRoute: typeof AppAccessRolesRoute
  AppAccessUsersRoute: typeof AppAccessUsersRoute
  AppGantryLoadingsRoute: typeof AppGantryLoadingsRoute
  AppStockReceiptsRoute: typeof AppStockReceiptsRoute
  AppStockTanksRoute: typeof AppStockTanksRoute
  AppTerminalPumpoverRoute: typeof AppTerminalPumpoverRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEwuraRoute: AppEwuraRoute,
  AppAccessRolesRoute: AppAccessRolesRoute,
  AppAccessUsersRoute: AppAccessUsersRoute,
  AppGantryLoadingsRoute: AppGantryLoadingsRoute,
  AppStockReceiptsRoute: AppStockReceiptsRoute,
  AppStockTanksRoute: AppStockTanksRoute,
  AppTerminalPumpoverRoute: AppTerminalPumpoverRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
