// Code generated from ISO 3166 country list (iban.com/country-codes). DO NOT EDIT BY HAND.
// Source: https://www.iban.com/country-codes
package setup

import "dfms/apps/models"

// defaultCountries is the full ISO 3166-1 catalogue (alpha-2, name, alpha-3, numeric).
var defaultCountries = []models.Country{
	{Code: "AF", Name: "Afghanistan", Alpha3: "AFG", Numeric: "004", IsActive: true},
	{Code: "AX", Name: "Åland Islands", Alpha3: "ALA", Numeric: "248", IsActive: true},
	{Code: "AL", Name: "Albania", Alpha3: "ALB", Numeric: "008", IsActive: true},
	{Code: "DZ", Name: "Algeria", Alpha3: "DZA", Numeric: "012", IsActive: true},
	{Code: "AS", Name: "American Samoa", Alpha3: "ASM", Numeric: "016", IsActive: true},
	{Code: "AD", Name: "Andorra", Alpha3: "AND", Numeric: "020", IsActive: true},
	{Code: "AO", Name: "Angola", Alpha3: "AGO", Numeric: "024", IsActive: true},
	{Code: "AI", Name: "Anguilla", Alpha3: "AIA", Numeric: "660", IsActive: true},
	{Code: "AQ", Name: "Antarctica", Alpha3: "ATA", Numeric: "010", IsActive: true},
	{Code: "AG", Name: "Antigua and Barbuda", Alpha3: "ATG", Numeric: "028", IsActive: true},
	{Code: "AR", Name: "Argentina", Alpha3: "ARG", Numeric: "032", IsActive: true},
	{Code: "AM", Name: "Armenia", Alpha3: "ARM", Numeric: "051", IsActive: true},
	{Code: "AW", Name: "Aruba", Alpha3: "ABW", Numeric: "533", IsActive: true},
	{Code: "AU", Name: "Australia", Alpha3: "AUS", Numeric: "036", IsActive: true},
	{Code: "AT", Name: "Austria", Alpha3: "AUT", Numeric: "040", IsActive: true},
	{Code: "AZ", Name: "Azerbaijan", Alpha3: "AZE", Numeric: "031", IsActive: true},
	{Code: "BS", Name: "Bahamas (the)", Alpha3: "BHS", Numeric: "044", IsActive: true},
	{Code: "BH", Name: "Bahrain", Alpha3: "BHR", Numeric: "048", IsActive: true},
	{Code: "BD", Name: "Bangladesh", Alpha3: "BGD", Numeric: "050", IsActive: true},
	{Code: "BB", Name: "Barbados", Alpha3: "BRB", Numeric: "052", IsActive: true},
	{Code: "BY", Name: "Belarus", Alpha3: "BLR", Numeric: "112", IsActive: true},
	{Code: "BE", Name: "Belgium", Alpha3: "BEL", Numeric: "056", IsActive: true},
	{Code: "BZ", Name: "Belize", Alpha3: "BLZ", Numeric: "084", IsActive: true},
	{Code: "BJ", Name: "Benin", Alpha3: "BEN", Numeric: "204", IsActive: true},
	{Code: "BM", Name: "Bermuda", Alpha3: "BMU", Numeric: "060", IsActive: true},
	{Code: "BT", Name: "Bhutan", Alpha3: "BTN", Numeric: "064", IsActive: true},
	{Code: "BO", Name: "Bolivia (Plurinational State of)", Alpha3: "BOL", Numeric: "068", IsActive: true},
	{Code: "BQ", Name: "Bonaire, Sint Eustatius and Saba", Alpha3: "BES", Numeric: "535", IsActive: true},
	{Code: "BA", Name: "Bosnia and Herzegovina", Alpha3: "BIH", Numeric: "070", IsActive: true},
	{Code: "BW", Name: "Botswana", Alpha3: "BWA", Numeric: "072", IsActive: true},
	{Code: "BV", Name: "Bouvet Island", Alpha3: "BVT", Numeric: "074", IsActive: true},
	{Code: "BR", Name: "Brazil", Alpha3: "BRA", Numeric: "076", IsActive: true},
	{Code: "IO", Name: "British Indian Ocean Territory (the)", Alpha3: "IOT", Numeric: "086", IsActive: true},
	{Code: "BN", Name: "Brunei Darussalam", Alpha3: "BRN", Numeric: "096", IsActive: true},
	{Code: "BG", Name: "Bulgaria", Alpha3: "BGR", Numeric: "100", IsActive: true},
	{Code: "BF", Name: "Burkina Faso", Alpha3: "BFA", Numeric: "854", IsActive: true},
	{Code: "BI", Name: "Burundi", Alpha3: "BDI", Numeric: "108", IsActive: true},
	{Code: "CV", Name: "Cabo Verde", Alpha3: "CPV", Numeric: "132", IsActive: true},
	{Code: "KH", Name: "Cambodia", Alpha3: "KHM", Numeric: "116", IsActive: true},
	{Code: "CM", Name: "Cameroon", Alpha3: "CMR", Numeric: "120", IsActive: true},
	{Code: "CA", Name: "Canada", Alpha3: "CAN", Numeric: "124", IsActive: true},
	{Code: "KY", Name: "Cayman Islands (the)", Alpha3: "CYM", Numeric: "136", IsActive: true},
	{Code: "CF", Name: "Central African Republic (the)", Alpha3: "CAF", Numeric: "140", IsActive: true},
	{Code: "TD", Name: "Chad", Alpha3: "TCD", Numeric: "148", IsActive: true},
	{Code: "CL", Name: "Chile", Alpha3: "CHL", Numeric: "152", IsActive: true},
	{Code: "CN", Name: "China", Alpha3: "CHN", Numeric: "156", IsActive: true},
	{Code: "CX", Name: "Christmas Island", Alpha3: "CXR", Numeric: "162", IsActive: true},
	{Code: "CC", Name: "Cocos (Keeling) Islands (the)", Alpha3: "CCK", Numeric: "166", IsActive: true},
	{Code: "CO", Name: "Colombia", Alpha3: "COL", Numeric: "170", IsActive: true},
	{Code: "KM", Name: "Comoros (the)", Alpha3: "COM", Numeric: "174", IsActive: true},
	{Code: "CD", Name: "Congo (the Democratic Republic of the)", Alpha3: "COD", Numeric: "180", IsActive: true},
	{Code: "CG", Name: "Congo (the)", Alpha3: "COG", Numeric: "178", IsActive: true},
	{Code: "CK", Name: "Cook Islands (the)", Alpha3: "COK", Numeric: "184", IsActive: true},
	{Code: "CR", Name: "Costa Rica", Alpha3: "CRI", Numeric: "188", IsActive: true},
	{Code: "CI", Name: "Côte d'Ivoire", Alpha3: "CIV", Numeric: "384", IsActive: true},
	{Code: "HR", Name: "Croatia", Alpha3: "HRV", Numeric: "191", IsActive: true},
	{Code: "CU", Name: "Cuba", Alpha3: "CUB", Numeric: "192", IsActive: true},
	{Code: "CW", Name: "Curaçao", Alpha3: "CUW", Numeric: "531", IsActive: true},
	{Code: "CY", Name: "Cyprus", Alpha3: "CYP", Numeric: "196", IsActive: true},
	{Code: "CZ", Name: "Czechia", Alpha3: "CZE", Numeric: "203", IsActive: true},
	{Code: "DK", Name: "Denmark", Alpha3: "DNK", Numeric: "208", IsActive: true},
	{Code: "DJ", Name: "Djibouti", Alpha3: "DJI", Numeric: "262", IsActive: true},
	{Code: "DM", Name: "Dominica", Alpha3: "DMA", Numeric: "212", IsActive: true},
	{Code: "DO", Name: "Dominican Republic (the)", Alpha3: "DOM", Numeric: "214", IsActive: true},
	{Code: "EC", Name: "Ecuador", Alpha3: "ECU", Numeric: "218", IsActive: true},
	{Code: "EG", Name: "Egypt", Alpha3: "EGY", Numeric: "818", IsActive: true},
	{Code: "SV", Name: "El Salvador", Alpha3: "SLV", Numeric: "222", IsActive: true},
	{Code: "GQ", Name: "Equatorial Guinea", Alpha3: "GNQ", Numeric: "226", IsActive: true},
	{Code: "ER", Name: "Eritrea", Alpha3: "ERI", Numeric: "232", IsActive: true},
	{Code: "EE", Name: "Estonia", Alpha3: "EST", Numeric: "233", IsActive: true},
	{Code: "SZ", Name: "Eswatini", Alpha3: "SWZ", Numeric: "748", IsActive: true},
	{Code: "ET", Name: "Ethiopia", Alpha3: "ETH", Numeric: "231", IsActive: true},
	{Code: "FK", Name: "Falkland Islands (the) [Malvinas]", Alpha3: "FLK", Numeric: "238", IsActive: true},
	{Code: "FO", Name: "Faroe Islands (the)", Alpha3: "FRO", Numeric: "234", IsActive: true},
	{Code: "FJ", Name: "Fiji", Alpha3: "FJI", Numeric: "242", IsActive: true},
	{Code: "FI", Name: "Finland", Alpha3: "FIN", Numeric: "246", IsActive: true},
	{Code: "FR", Name: "France", Alpha3: "FRA", Numeric: "250", IsActive: true},
	{Code: "GF", Name: "French Guiana", Alpha3: "GUF", Numeric: "254", IsActive: true},
	{Code: "PF", Name: "French Polynesia", Alpha3: "PYF", Numeric: "258", IsActive: true},
	{Code: "TF", Name: "French Southern Territories (the)", Alpha3: "ATF", Numeric: "260", IsActive: true},
	{Code: "GA", Name: "Gabon", Alpha3: "GAB", Numeric: "266", IsActive: true},
	{Code: "GM", Name: "Gambia (the)", Alpha3: "GMB", Numeric: "270", IsActive: true},
	{Code: "GE", Name: "Georgia", Alpha3: "GEO", Numeric: "268", IsActive: true},
	{Code: "DE", Name: "Germany", Alpha3: "DEU", Numeric: "276", IsActive: true},
	{Code: "GH", Name: "Ghana", Alpha3: "GHA", Numeric: "288", IsActive: true},
	{Code: "GI", Name: "Gibraltar", Alpha3: "GIB", Numeric: "292", IsActive: true},
	{Code: "GR", Name: "Greece", Alpha3: "GRC", Numeric: "300", IsActive: true},
	{Code: "GL", Name: "Greenland", Alpha3: "GRL", Numeric: "304", IsActive: true},
	{Code: "GD", Name: "Grenada", Alpha3: "GRD", Numeric: "308", IsActive: true},
	{Code: "GP", Name: "Guadeloupe", Alpha3: "GLP", Numeric: "312", IsActive: true},
	{Code: "GU", Name: "Guam", Alpha3: "GUM", Numeric: "316", IsActive: true},
	{Code: "GT", Name: "Guatemala", Alpha3: "GTM", Numeric: "320", IsActive: true},
	{Code: "GG", Name: "Guernsey", Alpha3: "GGY", Numeric: "831", IsActive: true},
	{Code: "GN", Name: "Guinea", Alpha3: "GIN", Numeric: "324", IsActive: true},
	{Code: "GW", Name: "Guinea-Bissau", Alpha3: "GNB", Numeric: "624", IsActive: true},
	{Code: "GY", Name: "Guyana", Alpha3: "GUY", Numeric: "328", IsActive: true},
	{Code: "HT", Name: "Haiti", Alpha3: "HTI", Numeric: "332", IsActive: true},
	{Code: "HM", Name: "Heard Island and McDonald Islands", Alpha3: "HMD", Numeric: "334", IsActive: true},
	{Code: "VA", Name: "Holy See (the)", Alpha3: "VAT", Numeric: "336", IsActive: true},
	{Code: "HN", Name: "Honduras", Alpha3: "HND", Numeric: "340", IsActive: true},
	{Code: "HK", Name: "Hong Kong", Alpha3: "HKG", Numeric: "344", IsActive: true},
	{Code: "HU", Name: "Hungary", Alpha3: "HUN", Numeric: "348", IsActive: true},
	{Code: "IS", Name: "Iceland", Alpha3: "ISL", Numeric: "352", IsActive: true},
	{Code: "IN", Name: "India", Alpha3: "IND", Numeric: "356", IsActive: true},
	{Code: "ID", Name: "Indonesia", Alpha3: "IDN", Numeric: "360", IsActive: true},
	{Code: "IR", Name: "Iran (Islamic Republic of)", Alpha3: "IRN", Numeric: "364", IsActive: true},
	{Code: "IQ", Name: "Iraq", Alpha3: "IRQ", Numeric: "368", IsActive: true},
	{Code: "IE", Name: "Ireland", Alpha3: "IRL", Numeric: "372", IsActive: true},
	{Code: "IM", Name: "Isle of Man", Alpha3: "IMN", Numeric: "833", IsActive: true},
	{Code: "IL", Name: "Israel", Alpha3: "ISR", Numeric: "376", IsActive: true},
	{Code: "IT", Name: "Italy", Alpha3: "ITA", Numeric: "380", IsActive: true},
	{Code: "JM", Name: "Jamaica", Alpha3: "JAM", Numeric: "388", IsActive: true},
	{Code: "JP", Name: "Japan", Alpha3: "JPN", Numeric: "392", IsActive: true},
	{Code: "JE", Name: "Jersey", Alpha3: "JEY", Numeric: "832", IsActive: true},
	{Code: "JO", Name: "Jordan", Alpha3: "JOR", Numeric: "400", IsActive: true},
	{Code: "KZ", Name: "Kazakhstan", Alpha3: "KAZ", Numeric: "398", IsActive: true},
	{Code: "KE", Name: "Kenya", Alpha3: "KEN", Numeric: "404", IsActive: true},
	{Code: "KI", Name: "Kiribati", Alpha3: "KIR", Numeric: "296", IsActive: true},
	{Code: "KP", Name: "Korea (the Democratic People's Republic of)", Alpha3: "PRK", Numeric: "408", IsActive: true},
	{Code: "KR", Name: "Korea (the Republic of)", Alpha3: "KOR", Numeric: "410", IsActive: true},
	{Code: "KW", Name: "Kuwait", Alpha3: "KWT", Numeric: "414", IsActive: true},
	{Code: "KG", Name: "Kyrgyzstan", Alpha3: "KGZ", Numeric: "417", IsActive: true},
	{Code: "LA", Name: "Lao People's Democratic Republic (the)", Alpha3: "LAO", Numeric: "418", IsActive: true},
	{Code: "LV", Name: "Latvia", Alpha3: "LVA", Numeric: "428", IsActive: true},
	{Code: "LB", Name: "Lebanon", Alpha3: "LBN", Numeric: "422", IsActive: true},
	{Code: "LS", Name: "Lesotho", Alpha3: "LSO", Numeric: "426", IsActive: true},
	{Code: "LR", Name: "Liberia", Alpha3: "LBR", Numeric: "430", IsActive: true},
	{Code: "LY", Name: "Libya", Alpha3: "LBY", Numeric: "434", IsActive: true},
	{Code: "LI", Name: "Liechtenstein", Alpha3: "LIE", Numeric: "438", IsActive: true},
	{Code: "LT", Name: "Lithuania", Alpha3: "LTU", Numeric: "440", IsActive: true},
	{Code: "LU", Name: "Luxembourg", Alpha3: "LUX", Numeric: "442", IsActive: true},
	{Code: "MO", Name: "Macao", Alpha3: "MAC", Numeric: "446", IsActive: true},
	{Code: "MK", Name: "North Macedonia", Alpha3: "MKD", Numeric: "807", IsActive: true},
	{Code: "MG", Name: "Madagascar", Alpha3: "MDG", Numeric: "450", IsActive: true},
	{Code: "MW", Name: "Malawi", Alpha3: "MWI", Numeric: "454", IsActive: true},
	{Code: "MY", Name: "Malaysia", Alpha3: "MYS", Numeric: "458", IsActive: true},
	{Code: "MV", Name: "Maldives", Alpha3: "MDV", Numeric: "462", IsActive: true},
	{Code: "ML", Name: "Mali", Alpha3: "MLI", Numeric: "466", IsActive: true},
	{Code: "MT", Name: "Malta", Alpha3: "MLT", Numeric: "470", IsActive: true},
	{Code: "MH", Name: "Marshall Islands (the)", Alpha3: "MHL", Numeric: "584", IsActive: true},
	{Code: "MQ", Name: "Martinique", Alpha3: "MTQ", Numeric: "474", IsActive: true},
	{Code: "MR", Name: "Mauritania", Alpha3: "MRT", Numeric: "478", IsActive: true},
	{Code: "MU", Name: "Mauritius", Alpha3: "MUS", Numeric: "480", IsActive: true},
	{Code: "YT", Name: "Mayotte", Alpha3: "MYT", Numeric: "175", IsActive: true},
	{Code: "MX", Name: "Mexico", Alpha3: "MEX", Numeric: "484", IsActive: true},
	{Code: "FM", Name: "Micronesia (Federated States of)", Alpha3: "FSM", Numeric: "583", IsActive: true},
	{Code: "MD", Name: "Moldova (the Republic of)", Alpha3: "MDA", Numeric: "498", IsActive: true},
	{Code: "MC", Name: "Monaco", Alpha3: "MCO", Numeric: "492", IsActive: true},
	{Code: "MN", Name: "Mongolia", Alpha3: "MNG", Numeric: "496", IsActive: true},
	{Code: "ME", Name: "Montenegro", Alpha3: "MNE", Numeric: "499", IsActive: true},
	{Code: "MS", Name: "Montserrat", Alpha3: "MSR", Numeric: "500", IsActive: true},
	{Code: "MA", Name: "Morocco", Alpha3: "MAR", Numeric: "504", IsActive: true},
	{Code: "MZ", Name: "Mozambique", Alpha3: "MOZ", Numeric: "508", IsActive: true},
	{Code: "MM", Name: "Myanmar", Alpha3: "MMR", Numeric: "104", IsActive: true},
	{Code: "NA", Name: "Namibia", Alpha3: "NAM", Numeric: "516", IsActive: true},
	{Code: "NR", Name: "Nauru", Alpha3: "NRU", Numeric: "520", IsActive: true},
	{Code: "NP", Name: "Nepal", Alpha3: "NPL", Numeric: "524", IsActive: true},
	{Code: "NL", Name: "Netherlands (the)", Alpha3: "NLD", Numeric: "528", IsActive: true},
	{Code: "NC", Name: "New Caledonia", Alpha3: "NCL", Numeric: "540", IsActive: true},
	{Code: "NZ", Name: "New Zealand", Alpha3: "NZL", Numeric: "554", IsActive: true},
	{Code: "NI", Name: "Nicaragua", Alpha3: "NIC", Numeric: "558", IsActive: true},
	{Code: "NE", Name: "Niger (the)", Alpha3: "NER", Numeric: "562", IsActive: true},
	{Code: "NG", Name: "Nigeria", Alpha3: "NGA", Numeric: "566", IsActive: true},
	{Code: "NU", Name: "Niue", Alpha3: "NIU", Numeric: "570", IsActive: true},
	{Code: "NF", Name: "Norfolk Island", Alpha3: "NFK", Numeric: "574", IsActive: true},
	{Code: "MP", Name: "Northern Mariana Islands (the)", Alpha3: "MNP", Numeric: "580", IsActive: true},
	{Code: "NO", Name: "Norway", Alpha3: "NOR", Numeric: "578", IsActive: true},
	{Code: "OM", Name: "Oman", Alpha3: "OMN", Numeric: "512", IsActive: true},
	{Code: "PK", Name: "Pakistan", Alpha3: "PAK", Numeric: "586", IsActive: true},
	{Code: "PW", Name: "Palau", Alpha3: "PLW", Numeric: "585", IsActive: true},
	{Code: "PS", Name: "Palestine, State of", Alpha3: "PSE", Numeric: "275", IsActive: true},
	{Code: "PA", Name: "Panama", Alpha3: "PAN", Numeric: "591", IsActive: true},
	{Code: "PG", Name: "Papua New Guinea", Alpha3: "PNG", Numeric: "598", IsActive: true},
	{Code: "PY", Name: "Paraguay", Alpha3: "PRY", Numeric: "600", IsActive: true},
	{Code: "PE", Name: "Peru", Alpha3: "PER", Numeric: "604", IsActive: true},
	{Code: "PH", Name: "Philippines (the)", Alpha3: "PHL", Numeric: "608", IsActive: true},
	{Code: "PN", Name: "Pitcairn", Alpha3: "PCN", Numeric: "612", IsActive: true},
	{Code: "PL", Name: "Poland", Alpha3: "POL", Numeric: "616", IsActive: true},
	{Code: "PT", Name: "Portugal", Alpha3: "PRT", Numeric: "620", IsActive: true},
	{Code: "PR", Name: "Puerto Rico", Alpha3: "PRI", Numeric: "630", IsActive: true},
	{Code: "QA", Name: "Qatar", Alpha3: "QAT", Numeric: "634", IsActive: true},
	{Code: "RE", Name: "Réunion", Alpha3: "REU", Numeric: "638", IsActive: true},
	{Code: "RO", Name: "Romania", Alpha3: "ROU", Numeric: "642", IsActive: true},
	{Code: "RU", Name: "Russian Federation (the)", Alpha3: "RUS", Numeric: "643", IsActive: true},
	{Code: "RW", Name: "Rwanda", Alpha3: "RWA", Numeric: "646", IsActive: true},
	{Code: "BL", Name: "Saint Barthélemy", Alpha3: "BLM", Numeric: "652", IsActive: true},
	{Code: "SH", Name: "Saint Helena, Ascension and Tristan da Cunha", Alpha3: "SHN", Numeric: "654", IsActive: true},
	{Code: "KN", Name: "Saint Kitts and Nevis", Alpha3: "KNA", Numeric: "659", IsActive: true},
	{Code: "LC", Name: "Saint Lucia", Alpha3: "LCA", Numeric: "662", IsActive: true},
	{Code: "MF", Name: "Saint Martin (French part)", Alpha3: "MAF", Numeric: "663", IsActive: true},
	{Code: "PM", Name: "Saint Pierre and Miquelon", Alpha3: "SPM", Numeric: "666", IsActive: true},
	{Code: "VC", Name: "Saint Vincent and the Grenadines", Alpha3: "VCT", Numeric: "670", IsActive: true},
	{Code: "WS", Name: "Samoa", Alpha3: "WSM", Numeric: "882", IsActive: true},
	{Code: "SM", Name: "San Marino", Alpha3: "SMR", Numeric: "674", IsActive: true},
	{Code: "ST", Name: "Sao Tome and Principe", Alpha3: "STP", Numeric: "678", IsActive: true},
	{Code: "SA", Name: "Saudi Arabia", Alpha3: "SAU", Numeric: "682", IsActive: true},
	{Code: "SN", Name: "Senegal", Alpha3: "SEN", Numeric: "686", IsActive: true},
	{Code: "RS", Name: "Serbia", Alpha3: "SRB", Numeric: "688", IsActive: true},
	{Code: "SC", Name: "Seychelles", Alpha3: "SYC", Numeric: "690", IsActive: true},
	{Code: "SL", Name: "Sierra Leone", Alpha3: "SLE", Numeric: "694", IsActive: true},
	{Code: "SG", Name: "Singapore", Alpha3: "SGP", Numeric: "702", IsActive: true},
	{Code: "SX", Name: "Sint Maarten (Dutch part)", Alpha3: "SXM", Numeric: "534", IsActive: true},
	{Code: "SK", Name: "Slovakia", Alpha3: "SVK", Numeric: "703", IsActive: true},
	{Code: "SI", Name: "Slovenia", Alpha3: "SVN", Numeric: "705", IsActive: true},
	{Code: "SB", Name: "Solomon Islands", Alpha3: "SLB", Numeric: "090", IsActive: true},
	{Code: "SO", Name: "Somalia", Alpha3: "SOM", Numeric: "706", IsActive: true},
	{Code: "ZA", Name: "South Africa", Alpha3: "ZAF", Numeric: "710", IsActive: true},
	{Code: "GS", Name: "South Georgia and the South Sandwich Islands", Alpha3: "SGS", Numeric: "239", IsActive: true},
	{Code: "SS", Name: "South Sudan", Alpha3: "SSD", Numeric: "728", IsActive: true},
	{Code: "ES", Name: "Spain", Alpha3: "ESP", Numeric: "724", IsActive: true},
	{Code: "LK", Name: "Sri Lanka", Alpha3: "LKA", Numeric: "144", IsActive: true},
	{Code: "SD", Name: "Sudan (the)", Alpha3: "SDN", Numeric: "729", IsActive: true},
	{Code: "SR", Name: "Suriname", Alpha3: "SUR", Numeric: "740", IsActive: true},
	{Code: "SJ", Name: "Svalbard and Jan Mayen", Alpha3: "SJM", Numeric: "744", IsActive: true},
	{Code: "SE", Name: "Sweden", Alpha3: "SWE", Numeric: "752", IsActive: true},
	{Code: "CH", Name: "Switzerland", Alpha3: "CHE", Numeric: "756", IsActive: true},
	{Code: "SY", Name: "Syrian Arab Republic", Alpha3: "SYR", Numeric: "760", IsActive: true},
	{Code: "TW", Name: "Taiwan (Province of China)", Alpha3: "TWN", Numeric: "158", IsActive: true},
	{Code: "TJ", Name: "Tajikistan", Alpha3: "TJK", Numeric: "762", IsActive: true},
	{Code: "TZ", Name: "Tanzania, United Republic of", Alpha3: "TZA", Numeric: "834", IsActive: true},
	{Code: "TH", Name: "Thailand", Alpha3: "THA", Numeric: "764", IsActive: true},
	{Code: "TL", Name: "Timor-Leste", Alpha3: "TLS", Numeric: "626", IsActive: true},
	{Code: "TG", Name: "Togo", Alpha3: "TGO", Numeric: "768", IsActive: true},
	{Code: "TK", Name: "Tokelau", Alpha3: "TKL", Numeric: "772", IsActive: true},
	{Code: "TO", Name: "Tonga", Alpha3: "TON", Numeric: "776", IsActive: true},
	{Code: "TT", Name: "Trinidad and Tobago", Alpha3: "TTO", Numeric: "780", IsActive: true},
	{Code: "TN", Name: "Tunisia", Alpha3: "TUN", Numeric: "788", IsActive: true},
	{Code: "TR", Name: "Türkiye", Alpha3: "TUR", Numeric: "792", IsActive: true},
	{Code: "TM", Name: "Turkmenistan", Alpha3: "TKM", Numeric: "795", IsActive: true},
	{Code: "TC", Name: "Turks and Caicos Islands (the)", Alpha3: "TCA", Numeric: "796", IsActive: true},
	{Code: "TV", Name: "Tuvalu", Alpha3: "TUV", Numeric: "798", IsActive: true},
	{Code: "UG", Name: "Uganda", Alpha3: "UGA", Numeric: "800", IsActive: true},
	{Code: "UA", Name: "Ukraine", Alpha3: "UKR", Numeric: "804", IsActive: true},
	{Code: "AE", Name: "United Arab Emirates (the)", Alpha3: "ARE", Numeric: "784", IsActive: true},
	{Code: "GB", Name: "United Kingdom of Great Britain and Northern Ireland (the)", Alpha3: "GBR", Numeric: "826", IsActive: true},
	{Code: "UM", Name: "United States Minor Outlying Islands (the)", Alpha3: "UMI", Numeric: "581", IsActive: true},
	{Code: "US", Name: "United States of America (the)", Alpha3: "USA", Numeric: "840", IsActive: true},
	{Code: "UY", Name: "Uruguay", Alpha3: "URY", Numeric: "858", IsActive: true},
	{Code: "UZ", Name: "Uzbekistan", Alpha3: "UZB", Numeric: "860", IsActive: true},
	{Code: "VU", Name: "Vanuatu", Alpha3: "VUT", Numeric: "548", IsActive: true},
	{Code: "VE", Name: "Venezuela (Bolivarian Republic of)", Alpha3: "VEN", Numeric: "862", IsActive: true},
	{Code: "VN", Name: "Viet Nam", Alpha3: "VNM", Numeric: "704", IsActive: true},
	{Code: "VG", Name: "Virgin Islands (British)", Alpha3: "VGB", Numeric: "092", IsActive: true},
	{Code: "VI", Name: "Virgin Islands (U.S.)", Alpha3: "VIR", Numeric: "850", IsActive: true},
	{Code: "WF", Name: "Wallis and Futuna", Alpha3: "WLF", Numeric: "876", IsActive: true},
	{Code: "EH", Name: "Western Sahara", Alpha3: "ESH", Numeric: "732", IsActive: true},
	{Code: "YE", Name: "Yemen", Alpha3: "YEM", Numeric: "887", IsActive: true},
	{Code: "ZM", Name: "Zambia", Alpha3: "ZMB", Numeric: "894", IsActive: true},
	{Code: "ZW", Name: "Zimbabwe", Alpha3: "ZWE", Numeric: "716", IsActive: true},
}
