package masterdata

import (
	"dfms/apps/auth/middleware"
	"dfms/pkg/db"
	"dfms/pkg/permissions"

	"github.com/gofiber/fiber/v3"
	"gorm.io/gorm"
)

func Router(app *fiber.App) {
	h := handler{db: db.Db}
	g := app.Group("/api/v1/master", middleware.PasetoMiddleware(), middleware.SessionVersionMiddleware())
	read := middleware.PermissionMiddleware(permissions.MasterdataRead, permissions.MasterdataManage, permissions.InventoryRead)
	write := middleware.PermissionMiddleware(permissions.MasterdataManage, permissions.MasterdataCreate, permissions.MasterdataUpdate)
	del := middleware.PermissionMiddleware(permissions.MasterdataManage, permissions.MasterdataDelete)
	customerRead := middleware.PermissionMiddleware(permissions.CustomersRead, permissions.MasterdataRead)
	customerCreate := middleware.PermissionMiddleware(permissions.CustomersCreate)
	customerUpdate := middleware.PermissionMiddleware(permissions.CustomersUpdate)
	customerWrite := middleware.PermissionMiddleware(permissions.CustomersCreate, permissions.CustomersUpdate)
	customerDelete := middleware.PermissionMiddleware(permissions.CustomersManage)
	catalogRead := middleware.PermissionMiddleware(permissions.MasterdataRead, permissions.MasterdataManage, permissions.InventoryRead, permissions.BillingRead, permissions.BillingManage)
	catalogWrite := middleware.PermissionMiddleware(permissions.MasterdataManage, permissions.MasterdataCreate, permissions.MasterdataUpdate, permissions.BillingManage)

	g.Get("/categories", read, h.listCategories)
	g.Post("/categories", write, h.createCategory)
	g.Put("/categories/:id", write, h.updateCategory)
	g.Delete("/categories/:id", del, h.deleteCategory)
	g.Get("/products", read, h.listProducts)
	g.Post("/products", write, h.createProduct)
	g.Put("/products/:id", write, h.updateProduct)
	g.Delete("/products/:id", del, h.deleteProduct)
	g.Get("/statuses", read, h.listStatuses)
	g.Post("/statuses", write, h.createStatus)
	g.Put("/statuses/:id", write, h.updateStatus)
	g.Delete("/statuses/:id", del, h.deleteStatus)
	g.Get("/uoms", read, h.listUOMs)
	g.Get("/countries", read, h.listCountries)
	g.Get("/tanks", read, h.listTanks)
	g.Post("/tanks", write, h.createTank)
	g.Put("/tanks/:id", write, h.updateTank)
	g.Delete("/tanks/:id", del, h.deleteTank)
	g.Get("/tanks/:id/attachments", read, h.listTankAttachments)
	g.Post("/tanks/:id/attachments", write, h.uploadTankAttachments)
	g.Get("/tanks/:id/attachments/:aid", read, h.downloadTankAttachment)
	g.Delete("/tanks/:id/attachments/:aid", write, h.deleteTankAttachment)
	g.Get("/vessels", read, h.listVessels)
	g.Post("/vessels", write, h.createVessel)
	g.Put("/vessels/:id", write, h.updateVessel)
	g.Delete("/vessels/:id", del, h.deleteVessel)
	g.Get("/depots", read, h.listDepots)
	g.Post("/depots", write, h.createDepot)
	g.Put("/depots/:id", write, h.updateDepot)
	g.Delete("/depots/:id", del, h.deleteDepot)
	g.Get("/customers", customerRead, h.listCustomers)
	g.Post("/customers", customerCreate, h.createCustomer)
	g.Put("/customers/:id", customerUpdate, h.updateCustomer)
	g.Delete("/customers/:id", customerDelete, h.deleteCustomer)
	g.Get("/customers/:uid", customerRead, h.getCustomer)
	g.Get("/customers/:id/billing-accounts", customerRead, h.listCustomerBillingAccounts)
	g.Post("/customers/:id/billing-accounts", customerWrite, h.createCustomerBillingAccount)
	g.Put("/customers/:id/billing-accounts/:aid", customerUpdate, h.updateCustomerBillingAccount)
	g.Delete("/customers/:id/billing-accounts/:aid", customerUpdate, h.deleteCustomerBillingAccount)
	g.Get("/customers/:id/attachments", customerRead, h.listCustomerAttachments)
	g.Post("/customers/:id/attachments", customerWrite, h.uploadCustomerAttachments)
	g.Get("/customers/:id/attachments/:aid", customerRead, h.downloadCustomerAttachment)
	g.Patch("/customers/:id/attachments/:aid", customerUpdate, h.patchCustomerAttachment)
	g.Delete("/customers/:id/attachments/:aid", customerUpdate, h.deleteCustomerAttachment)
	g.Get("/places/from-license", read, h.placeFromLicense)
	g.Get("/suppliers", read, h.listSuppliers)
	g.Post("/suppliers", write, h.createSupplier)
	g.Get("/suppliers/:id", read, h.getSupplier)
	g.Put("/suppliers/:id", write, h.updateSupplier)
	g.Delete("/suppliers/:id", del, h.deleteSupplier)
	g.Get("/suppliers/:id/billing-accounts", read, h.listSupplierBillingAccounts)
	g.Post("/suppliers/:id/billing-accounts", write, h.createSupplierBillingAccount)
	g.Put("/suppliers/:id/billing-accounts/:aid", write, h.updateSupplierBillingAccount)
	g.Delete("/suppliers/:id/billing-accounts/:aid", write, h.deleteSupplierBillingAccount)
	g.Get("/suppliers/:id/attachments", read, h.listSupplierAttachments)
	g.Post("/suppliers/:id/attachments", write, h.uploadSupplierAttachments)
	g.Get("/suppliers/:id/attachments/:aid", read, h.downloadSupplierAttachment)
	g.Delete("/suppliers/:id/attachments/:aid", write, h.deleteSupplierAttachment)
	g.Get("/transporters", read, h.listTransporters)
	g.Post("/transporters", write, h.createTransporter)
	g.Put("/transporters/:id", write, h.updateTransporter)
	g.Delete("/transporters/:id", del, h.deleteTransporter)
	g.Get("/drivers", read, h.listDrivers)
	g.Post("/drivers", write, h.createDriver)
	g.Put("/drivers/:id", write, h.updateDriver)
	g.Delete("/drivers/:id", del, h.deleteDriver)
	g.Get("/drivers/:id/attachments", read, h.listDriverAttachments)
	g.Post("/drivers/:id/attachments", write, h.uploadDriverAttachments)
	g.Get("/drivers/:id/attachments/:aid", read, h.downloadDriverAttachment)
	g.Delete("/drivers/:id/attachments/:aid", write, h.deleteDriverAttachment)
	g.Get("/trucks", read, h.listTrucks)
	g.Post("/trucks", write, h.createTruck)
	g.Get("/trucks/:id", read, h.getTruck)
	g.Put("/trucks/:id", write, h.updateTruck)
	g.Delete("/trucks/:id", del, h.deleteTruck)
	g.Get("/trucks/:id/tanks", read, h.listTruckTanks)
	g.Post("/trucks/:id/tanks", write, h.createTruckTank)
	g.Put("/trucks/:id/tanks/:tankId/calibration", write, h.saveTruckCalibration)
	g.Get("/trucks/:id/attachments", read, h.listTruckAttachments)
	g.Post("/trucks/:id/attachments", write, h.uploadTruckAttachments)
	g.Get("/trucks/:id/attachments/:aid", read, h.downloadTruckAttachment)
	g.Delete("/trucks/:id/attachments/:aid", write, h.deleteTruckAttachment)
	g.Get("/destinations", read, h.listDestinations)
	g.Post("/destinations", write, h.createDestination)
	g.Put("/destinations/:id", write, h.updateDestination)
	g.Delete("/destinations/:id", del, h.deleteDestination)
	g.Get("/districts", read, h.listDistricts)
	g.Post("/districts", write, h.createDistrict)
	g.Put("/districts/:id", write, h.updateDistrict)
	g.Delete("/districts/:id", del, h.deleteDistrict)
	g.Get("/lookups", catalogRead, h.lookups)
	g.Get("/tenders", catalogRead, h.listTenders)
	g.Post("/tenders", catalogWrite, h.createTender)
	g.Put("/tenders/:code", catalogWrite, h.updateTender)
	g.Get("/routes", catalogRead, h.listRoutes)
	g.Post("/routes", catalogWrite, h.createRoute)
	g.Put("/routes/:code", catalogWrite, h.updateRoute)
	g.Get("/delivery-methods", catalogRead, h.listDelivery)
	g.Post("/delivery-methods", catalogWrite, h.createDelivery)
	g.Put("/delivery-methods/:code", catalogWrite, h.updateDelivery)
	g.Get("/procurement-methods", catalogRead, h.listProcurement)
	g.Post("/procurement-methods", catalogWrite, h.createProcurement)
	g.Put("/procurement-methods/:code", catalogWrite, h.updateProcurement)
	g.Get("/contract-types", catalogRead, h.listContracts)
	g.Post("/contract-types", catalogWrite, h.createContract)
	g.Put("/contract-types/:code", catalogWrite, h.updateContract)
	g.Get("/pricing-natures", catalogRead, h.listPricing)
	g.Post("/pricing-natures", catalogWrite, h.createPricing)
	g.Put("/pricing-natures/:code", catalogWrite, h.updatePricing)
	g.Get("/billing-cycles", catalogRead, h.listCycles)
	g.Post("/billing-cycles", catalogWrite, h.createCycle)
	g.Put("/billing-cycles/:days", catalogWrite, h.updateCycle)
}

type handler struct{ db *gorm.DB }
